# Generated by Django 4.1.7 on 2023-09-30 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_remove_user_bio_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_date', models.DateField()),
                ('blocks_swipee', models.BooleanField()),
                ('user_likes_swipee', models.CharField(choices=[('T', 'To Swipe'), ('Y', 'Yes'), ('N', 'No')], default='T', max_length=1)),
                ('other_half', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
                ('swipee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('this_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pairing',
        ),
    ]
