# Generated by Django 4.1.7 on 2023-09-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_halfpairing_delete_pairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfpairing',
            name='blocks_swipee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='halfpairing',
            name='other_half',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.halfpairing'),
        ),
    ]
