# Generated by Django 4.1.7 on 2023-09-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_halfpairing_blocks_swipee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halfpairing',
            name='blocks_swipee',
        ),
    ]
