# Generated by Django 4.1.7 on 2023-11-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_bio_alter_userprofile_into_men_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='static/app/images/placeholder.png', upload_to='images'),
        ),
    ]
