# Generated by Django 4.1.7 on 2023-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_halfpairing_blocks_swipee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('O', 'Non-Binary')], max_length=1),
        ),
    ]
