# Generated by Django 4.1.7 on 2023-10-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='into_other',
            new_name='into_nb',
        ),
    ]
