# Generated by Django 4.1.7 on 2023-11-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='images/placeholder.png', upload_to='images/user_upload'),
        ),
    ]
