# Generated by Django 4.1.7 on 2023-10-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_into_other_userprofile_into_nb'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='halfpairing',
            unique_together={('this_user', 'swipee')},
        ),
    ]
