# Generated by Django 4.1.7 on 2023-08-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('O', 'Other')], max_length=1)),
                ('into_men', models.BooleanField()),
                ('into_women', models.BooleanField()),
                ('into_other', models.BooleanField()),
                ('picture', models.FileField(upload_to='')),
                ('bio', models.CharField(max_length=1500)),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='into_men',
        ),
        migrations.RemoveField(
            model_name='user',
            name='into_other',
        ),
        migrations.RemoveField(
            model_name='user',
            name='into_women',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
