# Generated by Django 4.1.7 on 2023-05-05 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_bid_alter_listing_start_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
