# Generated by Django 4.1.7 on 2023-05-05 17:34

import auctions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_start_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=models.SET(auctions.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
